#!/bin/bash

# Create the CA
cfssl gencert -initca ca-csr.json | cfssljson -bare ca

# Generate the auth service certs
cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=server \
  auth-csr.json | cfssljson -bare auth

# Generate the hello service certs
cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=server \
  hello-csr.json | cfssljson -bare hello

# Generate the jwt signing key pair
cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=signing \
  jwt-csr.json | cfssljson -bare jwt

# Generate the client certs
cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=client \
  client-csr.json | cfssljson -bare client
