#!/bin/bash
mkdir -p bin
go build -o bin/auth-admin ./auth-admin
go build -o bin/auth-client ./auth-client
go build -o bin/auth-server ./auth-server
go build -o bin/hello-client ./hello-client
go build -o bin/hello-server ./hello-server
