// Code generated by protoc-gen-go.
// source: hello.proto
// DO NOT EDIT!

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	Request
	Response
	LoginRequest
	LoginResponse
	User
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// The request message containing the user's name.
type Request struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the greeting.
type Response struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// The login request message containing the username and password.
type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// The login response message containing the JWT token.
type LoginResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type User struct {
	Email        string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Username     string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	PasswordHash string `protobuf:"bytes,3,opt,name=passwordHash" json:"passwordHash,omitempty"`
	IsAdmin      bool   `protobuf:"varint,4,opt,name=isAdmin" json:"isAdmin,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Request)(nil), "hello.Request")
	proto.RegisterType((*Response)(nil), "hello.Response")
	proto.RegisterType((*LoginRequest)(nil), "hello.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "hello.LoginResponse")
	proto.RegisterType((*User)(nil), "hello.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Hello service

type HelloClient interface {
	// Sends a greeting.
	Say(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Say(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/hello.Hello/Say", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	// Sends a greeting.
	Say(context.Context, *Request) (*Response, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(HelloServer).Say(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Hello_Say_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

// Client API for Auth service

type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/hello.Auth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AuthServer).Login(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x69, 0x9b, 0xd8, 0x38, 0x56, 0x85, 0xb1, 0x87, 0x25, 0x20, 0xc8, 0xa2, 0xe2, 0xa9,
	0x42, 0xbc, 0x79, 0xeb, 0x45, 0x7a, 0xf0, 0x14, 0xf1, 0x03, 0xac, 0x74, 0x68, 0x82, 0xc9, 0x6e,
	0xcc, 0x24, 0x8a, 0xdf, 0xde, 0x66, 0xff, 0x94, 0xc6, 0xdb, 0xfe, 0xe6, 0xcd, 0xbe, 0xb7, 0x33,
	0x0b, 0x67, 0x05, 0x55, 0x95, 0x59, 0x35, 0xad, 0xe9, 0x0c, 0xc6, 0x16, 0xe4, 0x35, 0xcc, 0x73,
	0xfa, 0xea, 0x89, 0x3b, 0x44, 0x88, 0xb4, 0xaa, 0x49, 0x4c, 0x6e, 0x26, 0x0f, 0xa7, 0xb9, 0x3d,
	0xcb, 0x5b, 0x48, 0x72, 0xe2, 0xc6, 0x68, 0x26, 0x14, 0x30, 0xaf, 0x89, 0x59, 0xed, 0x42, 0x4b,
	0x40, 0xf9, 0x02, 0x8b, 0x57, 0xb3, 0x2b, 0x75, 0x70, 0x4a, 0x21, 0xe9, 0x99, 0xda, 0x23, 0xb7,
	0x03, 0x0f, 0x5a, 0xa3, 0x98, 0x7f, 0x4c, 0xbb, 0x15, 0x53, 0xa7, 0x05, 0x96, 0x77, 0x70, 0xee,
	0x7d, 0x7c, 0xe4, 0x12, 0xe2, 0xce, 0x7c, 0x92, 0xf6, 0x2e, 0x0e, 0xe4, 0x37, 0x44, 0xef, 0x7b,
	0xbb, 0x41, 0xa5, 0x5a, 0x95, 0x55, 0x50, 0x2d, 0x8c, 0xc2, 0xa7, 0xff, 0xc2, 0x25, 0x2c, 0x42,
	0xd8, 0x46, 0x71, 0x21, 0x66, 0x56, 0x1f, 0xd5, 0x86, 0x31, 0x4b, 0x5e, 0x6f, 0xeb, 0x52, 0x8b,
	0x68, 0x2f, 0x27, 0x79, 0xc0, 0xec, 0x11, 0xe2, 0xcd, 0xb0, 0x34, 0xbc, 0x87, 0xd9, 0x9b, 0xfa,
	0xc5, 0x8b, 0x95, 0x5b, 0xa8, 0x1f, 0x3b, 0xbd, 0x3c, 0xb0, 0x7b, 0x7e, 0xf6, 0x0c, 0xd1, 0xba,
	0xef, 0x0a, 0xcc, 0x20, 0xb6, 0x73, 0xe1, 0x95, 0xef, 0x38, 0xde, 0x56, 0xba, 0x1c, 0x17, 0xdd,
	0xdd, 0x8f, 0x13, 0xfb, 0x4d, 0x4f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x24, 0x32, 0x66, 0x36,
	0xb5, 0x01, 0x00, 0x00,
}
