#!/bin/bash

# Create the CA
cfssl gencert -initca certs/ca-csr.json | cfssljson -bare ca

# Generate the auth service certs
cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=certs/ca-config.json \
  -profile=server \
  certs/auth-csr.json | cfssljson -bare auth

# Generate the hello service certs
cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=certs/ca-config.json \
  -profile=server \
  certs/hello-csr.json | cfssljson -bare hello

# Generate the jwt signing key pair
cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=certs/ca-config.json \
  -profile=signing \
  certs/jwt-csr.json | cfssljson -bare jwt

# Generate the client certs
cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=certs/ca-config.json \
  -profile=client \
  certs/client-csr.json | cfssljson -bare client
